# Generated by Django 3.1.7 on 2021-05-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_tour_flightfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='flightfrom',
            field=models.CharField(choices=[('Warszawa', 'Warszawa'), ('Katowice', 'Katowice'), ('Wrocław', 'Wrocław'), ('Gdańsk', 'Gdańsk'), ('Kraków', 'Kraków')], max_length=20),
        ),
    ]
