# Generated by Django 3.1.7 on 2021-05-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210526_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='time',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
