# Generated by Django 3.1.7 on 2021-05-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_tour_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='time',
            new_name='days',
        ),
    ]
