# Generated by Django 3.1.7 on 2021-05-27 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210526_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='flightto',
            field=models.CharField(default='Monachium', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
